FROM golang:1.23 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o servicoa ./cmd/servicoa/servicoa.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/servicoa /app/
EXPOSE 8081
ENTRYPOINT ["/app/servicoa"]

